const inventaryProducts = [
  {
    title: "Cotton Carbon",
    price: 7340,
    amount: 1,
    image: "COTTONCARBON.jpg",
    image2: "COTTONCARBON2.jpg",
    image3: "COTTONCARBON3.jpg",
    image4: "COTTONCARBON4.jpg",
    stock: 5,
    category: "leggins",
    type: "allProducts",
    id: 1,
  },
  {
    title: "Cotton Black",
    price: 7340,
    amount: 1,
    image: "COTTONBLACK.jpg",
    image2: "COTTONBLACK2.jpg",
    image3: "COTTONBLACK3.jpg",
    image4: "COTTONBLACK4.jpg",
    stock: 3,
    category: "leggins",
    type: "allProducts",
    id: 2,
  },
  {
    title: "Cotton Grey",
    price: 7340,
    amount: 1,
    image: "COTTONGREY.jpg",
    image2: "COTTONGREY2.jpg",
    image3: "COTTONGREY3.jpg",
    image4: "COTTONGREY4.jpg",
    stock: 4,
    category: "leggins",
    type: "allProducts",
    id: 3,
  },
  {
    title: "Cotton Navy",
    price: 7340,
    amount: 1,
    image: "COTTONNAVY.jpg",
    image2: "COTTONNAVY2.jpg",
    image3: "COTTONNAVY3.jpg",
    image4: "COTTONNAVY4.jpg",
    stock: 5,
    category: "leggins",
    type: "allProducts",
    id: 4,
  },
  {
    title: "Herradura",
    price: 8740,
    amount: 1,
    image: "HERRADURA.jpg",
    image2: "HERRADURA2.jpg",
    image3: "HERRADURA3.jpg",
    image4: "HERRADURA4.jpg",
    stock: 3,
    category: "leggins",
    type: "allProducts",
    id: 5,
  },
  {
    title: "Orchind",
    price: 8740,
    amount: 1,
    image: "ORCHIND.jpg",
    image2: "ORCHIND2.jpg",
    image3: "ORCHIND3.jpg",
    image4: "ORCHIND4.jpg",
    stock: 2,
    category: "leggins",
    type: "allProducts",
    id: 6,
  },
  {
    title: "Saffron",
    price: 8740,
    amount: 1,
    image: "SAFFRON.jpg",
    image2: "SAFFRON2.jpg",
    image3: "SAFFRON3.jpg",
    image4: "SAFFRON4.jpg",
    stock: 5,
    category: "leggins",
    type: "allProducts",
    id: 7,
  },
  {
    title: "Toucan",
    price: 8740,
    amount: 1,
    image: "TOUCAN.jpg",
    image2: "TOUCAN2.jpg",
    image3: "TOUCAN3.jpg",
    image4: "TOUCAN4.jpg",
    stock: 6,
    category: "leggins",
    type: "allProducts",
    id: 8,
  },
  {
    title: "Toucan Top",
    price: 5390,
    amount: 1,
    image: "TOUCANTOP.jpg",
    image2: "TOUCANTOP2.jpg",
    image3: "TOUCANTOP3.jpg",
    image4: "TOUCANTOP4.jpg",
    stock: 4,
    category: "tops",
    type: "allProducts",
    id: 9,
  },
  {
    title: "Orchid Top",
    price: 5390,
    amount: 1,
    image: "ORCHINDTOP.jpg",
    image2: "ORCHINDTOP2.jpg",
    image3: "ORCHINDTOP3.jpg",
    image4: "ORCHINDTOP4.jpg",
    stock: 7,
    category: "tops",
    type: "allProducts",
    id: 10,
  },
  {
    title: "Saffron Top",
    price: 5390,
    amount: 1,
    image: "SAFFRONTOP.jpg",
    image2: "SAFFRONTOP2.jpg",
    image3: "SAFFRONTOP3.jpg",
    image4: "SAFFRONTOP4.jpg",
    stock: 6,
    category: "tops",
    type: "allProducts",
    id: 11,
  },
  {
    title: "Herradura Top",
    price: 5390,
    amount: 1,
    image: "HERRADURATOP.jpg",
    image2: "HERRADURATOP2.jpg",
    image3: "HERRADURATOP3.jpg",
    image4: "HERRADURATOP4.jpg",
    stock: 3,
    category: "tops",
    type: "allProducts",
    id: 12,
  },
  {
    title: "Peace Top",
    price: 5390,
    amount: 1,
    image: "PEACETOP.jpg",
    image2: "PEACETOP2.jpg",
    image3: "PEACETOP3.jpg",
    image4: "PEACETOP4.jpg",
    stock: 7,
    category: "tops",
    type: "allProducts",
    id: 13,
  },
  {
    title: "Ace Top",
    price: 5390,
    amount: 1,
    image: "ACETOP.jpg",
    image2: "ACETOP2.jpg",
    image3: "ACETOP3.jpg",
    image4: "ACETOP4.jpg",
    stock: 8,
    category: "tops",
    type: "allProducts",
    id: 14,
  },
  {
    title: "Speed Top",
    price: 5390,
    amount: 1,
    image: "SPEEDTOP.jpg",
    image2: "SPEEDTOP2.jpg",
    image3: "SPEEDTOP3.jpg",
    image4: "SPEEDTOP4.jpg",
    stock: 3,
    category: "tops",
    type: "allProducts",
    id: 15,
  },
  {
    title: "Leopard Top",
    price: 5390,
    amount: 1,
    image: "LEOPARDTOP.jpg",
    image2: "LEOPARDTOP2.jpg",
    image3: "LEOPARDTOP3.jpg",
    image4: "LEOPARDTOP4.jpg",
    stock: 6,
    category: "tops",
    type: "allProducts",
    id: 16,
  },
];

export default inventaryProducts;
